# Generated by Django 5.2.17 on 2026-08-17 09:10

import counters.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(help_text='Es. "esp32-cucina", "shortcut-iphone".', max_length=100, verbose_name='nome')),
                ('key', models.CharField(db_index=True, default=counters.models.generate_key, editable=False, max_length=64, unique=True, verbose_name='chiave')),
                ('is_active', models.BooleanField(default=True, verbose_name='attivo')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ultimo utilizzo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificato da')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'token API',
                'verbose_name_plural': 'token API',
                'ordering': ('user__username', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='valore corrente')),
                ('color', models.CharField(default='#3b82f6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa il formato #RRGGBB.')], verbose_name='colore')),
                ('is_active', models.BooleanField(default=True, help_text='Un counter non attivo resta leggibile ma rifiuta le scritture e sparisce dalle griglie dei display.', verbose_name='attivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificato da')),
            ],
            options={
                'verbose_name': 'counter',
                'verbose_name_plural': 'counter',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('refresh_interval', models.PositiveIntegerField(default=2000, help_text='Ogni quanti millisecondi il display rilegge i valori.', verbose_name='intervallo di aggiornamento (ms)')),
                ('delta_highlight_duration', models.PositiveIntegerField(default=4000, help_text='Per quanti millisecondi resta visibile il badge +/- dopo una variazione.', verbose_name='durata evidenziazione variazione (ms)')),
                ('grid_columns', models.PositiveSmallIntegerField(blank=True, help_text='Lascia vuoto per calcolarle automaticamente dal numero di counter.', null=True, verbose_name='colonne della griglia')),
                ('add_key', models.CharField(default='+', max_length=1, verbose_name='tasto somma')),
                ('subtract_key', models.CharField(default='-', max_length=1, verbose_name='tasto sottrazione')),
                ('set_key', models.CharField(default='*', max_length=1, verbose_name='tasto impostazione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificato da')),
            ],
            options={
                'verbose_name': 'display',
                'verbose_name_plural': 'display',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, help_text='Tasto che seleziona questo counter. Lascia vuoto per nessuna scorciatoia.', max_length=1, verbose_name='tasto')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='posizione')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.counter', verbose_name='counter')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.display', verbose_name='display')),
            ],
            options={
                'verbose_name': 'counter del display',
                'verbose_name_plural': 'counter del display',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='display',
            name='counters',
            field=models.ManyToManyField(related_name='displays', through='counters.DisplayCounter', to='counters.counter', verbose_name='counter'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificato il')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificato da')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tag',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='counters.tag', verbose_name='tag'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('add', 'add'), ('subtract', 'subtract'), ('set', 'set')], max_length=10, verbose_name='operazione')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='valore richiesto')),
                ('value_before', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='valore precedente')),
                ('value_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='valore risultante')),
                ('source', models.CharField(choices=[('api', 'api'), ('display', 'display'), ('admin', 'admin')], default='api', max_length=10, verbose_name='origine')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='eseguita il')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='counters.counter', verbose_name='counter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'transazione',
                'verbose_name_plural': 'transazioni',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='displaycounter',
            constraint=models.UniqueConstraint(fields=('display', 'counter'), name='unique_display_counter'),
        ),
        migrations.AddConstraint(
            model_name='displaycounter',
            constraint=models.UniqueConstraint(condition=models.Q(('key__gt', '')), fields=('display', 'key'), name='unique_display_key'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['counter', '-created_at'], name='counters_tr_counter_9a852a_idx'),
        ),
    ]
