# Generated by Django 5.2.17 on 2026-08-17 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Un carattere, oppure un tasto come F1, ArrowUp, Enter, Space.', max_length=20, verbose_name='tasto')),
                ('action', models.CharField(choices=[('add', 'add'), ('subtract', 'subtract'), ('set', 'set')], default='add', max_length=10, verbose_name='azione')),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='quantità')),
                ('label', models.CharField(blank=True, help_text='Promemoria per l\'admin, es. "Fritto +1".', max_length=60, verbose_name='etichetta')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.counter', verbose_name='counter')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counters.display', verbose_name='display')),
            ],
            options={
                'verbose_name': 'hotkey',
                'verbose_name_plural': 'hotkey',
                'ordering': ('key',),
                'constraints': [models.UniqueConstraint(fields=('display', 'key'), name='unique_display_hotkey')],
            },
        ),
    ]
